### ISSUE TITLE
I could not make pull request

### ISSUE THREAD

**Issue by mishin** [szabgab/perlmaven.com#450]
https://github.com/szabgab/perlmaven.com/blob/fb2c8d96b79ba13c0c73041d39564023cfa92d83/sites/ru/pages/otkrytie-i-chtenie-faylov.txt

Hi Gabor!
I found mistype in 
http://ru.perlmaven.com/otkrytie-i-chtenie-faylov
but I cannot edit it, when I fork https://github.com/szabgab/perlmaven.com
these page is not available

**Comment by szabgab** [comment]
You probbably already had a fork from earlier. The simplest thing might be to delete your previous fork from GitHub and the fork again.

**Comment by mishin** [comment]
Waw, Gabor, it works, most hardly was to find where repository could be deleted!
