### ISSUE TITLE
Multiple Attachments

### ISSUE THREAD

**Issue by mancusor0** [szabgab/perlmaven.com#543]
Deal Perl Maven,

How could I create an email with multiple attachments?

I need my Perl script to email out PDF's and Email files to various distribution lists.

Thanks

**Comment by szabgab** [comment]
What do you have so far?

**Comment by mancusor0** [comment]
Hi Perl Maven,

Thanks I figured it out.  The sample you posted did not include how to add file attachments. I was using to using MIME::Lite and the command was "attach".  For this module, I needed to use "attach_file".

I added this snippet to your sample just after the transport section.  I'm assuming that I might be working with multiple attachments and am sending this to my "Mail" subroutine as a string with the filenames separated by a semicolon.

  #add attachments.  (these must be looped through)
  my @attachfile = split /;/,$attach;
  while (my $attachf = shift (@attachfile))
  {
    if (defined($attachf)){
      $email->attach_file($attachf);
    }
  }

**Comment by mancusor0** [comment]
Here's a sample sub routing that I wrote.
[MailStuffer.zip](https://github.com/szabgab/perlmaven.com/files/4119360/MailStuffer.zip)

**Comment by szabgab** [comment]
Thanks for sending your solution. I'll add it to an article.
