### ISSUE TITLE
Dead Link in https://perlmaven.com/perl-based-open-source-products

### ISSUE THREAD

**Issue by soonix** [szabgab/perlmaven.com#544]
file in this repository: `sites/en/pages/perl-based-open-source-products.txt`

under "Mailing list", the link to **Minimalist** points to a domain parking site.
On archive.org, the latest "working" version is [from June 2014](https://web.archive.org/web/20140620123325/http://www.mml.org.ua:80/). There seems to exist a fork on github [madroach/minimalist](https://github.com/madroach/minimalist) with latest commit in November 2014.

Since it is no longer maintained (the page on archive.org explicitly says so), Unless someone resurrects it, I think it should be removed from this list...

**Comment by szabgab** [comment]
thank you for reporting and fixing.
