### ISSUE TITLE
Alternative installation method for cpanm

### ISSUE THREAD

**Issue by procrastinat0r** [szabgab/perlmaven.com#546]
https://github.com/szabgab/perlmaven.com/blob/d265a472e6596c458dedcb7bc3cff184c50aee34/sites/en/pages/cpanm.txt#L22

Hi Gregor,

installation of cpanm is also possible via
<code>
cpan App::cpanminus
</code>

Thanks for your activities around Perl.

BR

**Comment by szabgab** [comment]
Well it is, but for that you need to configure the cpan client and probably run that as root  right?

**Comment by procrastinat0r** [comment]
You are right.  There is a work around using [local::lib](http://search.cpan.org/perldoc/local::lib#The_bootstrapping_technique) but it is much more complicated if `cpan` is not yet in use already. And also Tatsuhiko Miyagawa does no mention it in his installation guide. He also refers to `curl`, so better stay with that.   
Thanks.
