### ISSUE TITLE
Comment on counter-with-dancer-using-in-memory-sqlite-database.txt

### ISSUE THREAD

**Issue by matthewpersico** [szabgab/perlmaven.com#556]
I *think* there is a way to persist and reload an SQLite DB. Maybe put the persist commands in an `END` block and the reload in a BEGIN block.

**Comment by szabgab** [comment]
I am not sure what persist command do you mean. As I understand this DB is per process and it only lives in the memory.

**Comment by matthewpersico** [comment]
My bad. I could have sworn there was a way to dump and load an in memory db.

**Comment by szabgab** [comment]
:+1:
