### ISSUE TITLE
Typo line 43

### ISSUE THREAD

**Issue by bernuli** [szabgab/perlmaven.com#558]
On should be One

**Comment by szabgab** [comment]
On which page?

**Comment by bernuli** [comment]
typo is on https://perlmaven.com/escaping-regexes

sorry I thought I was commenting on perlmaven.com/sites/en/pages/escaping-regexes.txt

**Comment by szabgab** [comment]
Thanks. I found and fixed another one of those typos.

**Comment by szabgab** [comment]
And no problem, it is really unclear from the site. I'll add a link that pre-fills the form
