### ISSUE TITLE
Did you ever do an article on how to do this for GitHub?

### ISSUE THREAD

**Issue by matthewpersico** [szabgab/perlmaven.com#559]
https://perlmaven.com/bitbucket-pipelines-testing-perl-projects

**Comment by szabgab** [comment]
Like this? https://perlmaven.com/github-actions-ci-job-for-test-class

**Comment by szabgab** [comment]
or these?
https://perlmaven.com/github-actions-showing-error-log-on-linux-mac-windows
https://perlmaven.com/setup-github-actions

or these slides: https://code-maven.com/slides/github-ci/actions

**Comment by matthewpersico** [comment]
🤦‍♂️ You have a nice big search box on the PerlMaven site and when I type "github" into it, these and other articles pop up. That's what happens before one has a decent cup of coffee.  Sorry to bother you.
