### ISSUE TITLE
get keys values from array of hashes

### ISSUE THREAD

**Issue by zemlik** [szabgab/perlmaven.com#560]
hello, I'm not very good at this. I can get the keys and values from a regular hash and write them as a .csv file to disk.
I can get the values from individual keys in an array of hashes, which your excellent web site showed how to make.
 $L_vars[0]={
image_file=>"my_images",
start_frame=>30,
end_frame=>50
}
but I'm having problems getting the keys, values from that as can't find the syntax to address the hash.
help appreciated.
regards
mick

**Comment by szabgab** [comment]
Look at "dereferencing refernces to hashes"
`%{$L_vars[0]}`  is the hash. From there you can figure it out.
