### ISSUE TITLE
Dumping GitHub Action error logs

### ISSUE THREAD

**Issue by trwyant** [szabgab/perlmaven.com#566]
Thanks for blog post https://perlmaven.com/install-developer-dependencies-first-test-css

After applying your pull request to https://metacpan.org/dist/Date-ManipX-Almanac I decided to dive into the the file to try to bend it to my own biases. The most significant change so far was to try to run multiple versions of Perl -- the latest available, and the oldest the distro supports (or the oldest available, if they're different). The distro your pull request was against was written to Perl 5.10, which caused no problem. The next one I tried was written to Perl 5.6.2 and produced exactly the error you describe under darwin and ubuntu (Windows uses Strawberry and does not go back before 5.14). Lacking a way to troubleshoot, I simply pretended Perl 5.6.2 was not available on that platform and used 5.8.

Now I have a way to dig under the hood and find out what is really going on. Thanks again.

**Comment by szabgab** [comment]
Nice. Would you like to post this on some blog. e.g. on https://dev.to/ ?
