### ISSUE TITLE
Strange build/test errors in Github Actions

### ISSUE THREAD

**Issue by sbakker** [szabgab/perlmaven.com#567]
https://perlmaven.com/setup-github-actions

Hi,

I tried your suggested setup for a `Dist::Zilla` distribution on my own repo (https://github.com/sbakker/perl-Term-CLI). For some reason I needed to add a `cpanm --notest Dist::Zilla` because I was getting `dzil: command not found` errors.

I now get it to run the tests, but I'm getting failures which do not appear when I pull the Docker image on my laptop and run the tests in there myself. The released module on CPAN also does not show errors in the test results.

I'm guessing that, since this module uses builds on `Term::ReadLine` and `Term::ReadLine::Gnu` specifically, the Docker image on Github runs the tests in some bizarre (pseudo-)terminal setup (I'm getting errors from deep within `Term::ReadKey`).

Any hints on how to debug this would be more than welcome.

Cheers,
Steven

**Comment by szabgab** [comment]
Nice.
If you think these are bugs, you might want to open issues for the respective modules. I also see that `Term::ReadLine::Gnu` has GA enabled but `Term::ReadKey` has not. Maybe send a PR to that.

**Comment by sbakker** [comment]
Thanks. It seems someone else noticed this because I found a similar issue in their bug tracker. Looks like `Term::ReadKey` is actually not affected, so that's a red herring. The `Term::ReadLine::Gnu` has checks and exceptions built in for specific `TERM` values, apparently in response to earlier bug reports.

BTW, what is "GA"?
