### ISSUE TITLE
Mismatched braces in first listing.

### ISSUE THREAD

**Issue by marnixava** [szabgab/perlmaven.com#568]
https://perlmaven.com/indexing-emails-in-an-mbox

No biggie.  Just noticed an extra final closing brace in the first listing in this article.

I would love to learn more.  I need to read more of your articles.  I'm not sure what is the advantage of using main::cnt instead of just declaring a global "my cnt;" somewhere early on.  I'll try to read & learn more from your articles.

Peace -- Marnix

**Comment by szabgab** [comment]
Thanks. I fixed the bug.

I think I just did not want to bother to declare that variable I was using for debugging and that I would remove after I am done with the debugging.
This might help with the variable thing: https://perlmaven.com/package-variables-and-lexical-variables-in-perl
