### ISSUE TITLE
missing ';'

### ISSUE THREAD

**Issue by jgpawletko** [szabgab/perlmaven.com#574]
Thank you for your awesome Perl website! 
I noticed that there was a missing semi-colon for this example:
https://github.com/szabgab/perlmaven.com/blob/15c9857ac77fc0ed7efe62aae096ebbc572e89bf/sites/en/pages/trim.txt#LL48C23-L48C23

Cheers!

**Comment by szabgab** [comment]
Do you mean a the end of the statement?

You don't need semicolon at the end of the last statement.

**Comment by szabgab** [comment]
I assume my previous comment was the correct answer. Closing.
