### ISSUE TITLE
Covert a strins a name fuction

### ISSUE THREAD

**Issue by xohub27** [szabgab/perlmaven.com#576]
https://es.perlmaven.com/ayuda

**Please,** I need your help.  I had been created the  string: **$averages**
**$averages**="get_averages(%HoH, '2023-01-01','2023-01-02','2023-01-03',)"; 

**#The string above has been created for call a function to calculate averages for the days the user know averages. (get_averages)**

The variable **$averages** is a string variable, BUT it must a call the **function get_averages** with the parameters  that the user had been selected.

**Please,** will you help  guide me **how to call the function get_averages**.

Regards
Xochitl

**Comment by szabgab** [comment]
Try `eval $averages` but note, this will open you application to nasty attack vector. In my opinion if you need to call a function that is provided as a string in the way you described, that means there are some security issues in the project.

**Comment by xohub27** [comment]
Thanks a lot Gábor, I had been use *eval $averages function*,  I hope not
open for any nasty attack, my work environment has  some security issues

Regards
Xòchitl

**Comment by szabgab** [comment]
If you `eval` a string that comes from an external source then you execute some code that comes from that source. That can be anything. If that source is somehow compromised. e.g. even if it is the log-file created by your web application, then someone might be able to use it as an attack vector.
