### ISSUE TITLE
What prints the error?

### ISSUE THREAD

**Issue by jidanni** [szabgab/perlmaven.com#583]
On https://perlmaven.com/out-of-memory
- Does Linux print "Out of memory"?
- Does perl print "Out of memory"?

Couldn't the thing saying those words identify itself?

**Comment by szabgab** [comment]
It's the OS (In this case Linux) that kills the program and says it is out of memory.

**Comment by jidanni** [comment]
Thanks! [I let them know](https://lore.kernel.org/stable/9399ce7b9ffa0ff6da062e9f65543362@jidanni.org/).

**Comment by jidanni** [comment]
In https://lore.kernel.org/stable/20231126092044.GA7407@1wt.eu/ they say it was in fact perl printing that message.

**Comment by szabgab** [comment]
good to know
